Resources:
  SesForwarderLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref SesForwarderLambdaFunction
      Principal: ses.amazonaws.com
      SourceAccount: !Ref AWS::AccountId

