Resources:
  SesRuleSet:
    Type: AWS::SES::ReceiptRuleSet
  SesS3Rule:
    Type: AWS::SES::ReceiptRule
    Properties:
      Rule: 
        Actions:
          - S3Action:
              BucketName: !Ref EmailsBucket
              ObjectKeyPrefix: emails
          - LambdaAction:
              FunctionArn: !GetAtt SesForwarderLambdaFunction.Arn
      RuleSetName: !Ref SesRuleSet
    
Outputs:
  SesRuleSetName:
    Value:
      Ref: SesRuleSet
    

